# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
version: 1
policy:
  pullRequests: public
tasks:
  $let:
    HEAD_REV:
      $if: 'tasks_for == "github-pull-request"'
      then: '${event.pull_request.head.sha}'
      else:
        $if: 'tasks_for == "github-push"'
        then: '${event.after}'
        else: '${event.release.tag_name}'

    REPO_URL:
      $if: 'tasks_for == "github-pull-request"'
      then: '${event.pull_request.head.repo.html_url}'
      else: '${event.repository.html_url}'

    OWNER: '${event.sender.login}@users.noreply.github.com'
  in:
    - schedulerId: taskcluster-github
      created: {$fromNow: ''}
      deadline: {$fromNow: '4 hours'}
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      retries: 5
      payload:
        maxRunTime: 600
        image: python:3.7-slim
        command:
          - /bin/bash
          - --login
          - -cx
          - exit 0
      metadata:
        owner: '${OWNER}'
        source: '${REPO_URL}/raw/${HEAD_REV}/.taskcluster.yml'
        name: 'noop'
        description: 'noop'
