language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      dist: xenial
      env:
        - TOXENV=py36
      sudo: true
    - python: 3.7
      dist: xenial
      env:
        - TOXENV=py37
      sudo: true

install:
    - travis_retry pip install tox
script:
    - tox
after_script:
    - tox -e coveralls

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
