work_dir: /tmp/work
artifact_dir: /tmp/artifacts
taskcluster_scope_prefix: "project:releng:signing:"
verbose: true
local_notarization_accounts: ["account1"]
mac_config:
    dep:
        notarize_type: multi_account
        signing_keychain: /path/to/dep.keychain
        base_bundle_id: org.mozilla.firefox_dep
        identity: ...
        keychain_password: ...
        pkg_cert_id: ...
        apple_notarization_account: ...
        apple_notarization_password: ...
        notarization_poll_timeout: 900
